import type { ThemeMode } from './tokens';

export interface BaseMaterialThemeOptions {
  seedColor: string;
  secondaryColor: string;
  tertiaryColor: string;
  neutralColor: string;
  neutralVariantColor: string;
  successColor: string;
  warningColor: string;
}

export const DEFAULT_THEME_OPTIONS: BaseMaterialThemeOptions = {
  seedColor: '#2563eb',
  secondaryColor: '#7c3aed',
  tertiaryColor: '#f97316',
  neutralColor: '#6b6f7c',
  neutralVariantColor: '#687385',
  successColor: '#4caf50',
  warningColor: '#ff9800',
};

export const FALLBACK_COLOR_TOKENS = [
  'primary',
  'onPrimary',
  'primaryContainer',
  'onPrimaryContainer',
  'secondary',
  'onSecondary',
  'secondaryContainer',
  'onSecondaryContainer',
  'tertiary',
  'onTertiary',
  'tertiaryContainer',
  'onTertiaryContainer',
  'error',
  'onError',
  'errorContainer',
  'onErrorContainer',
  'background',
  'onBackground',
  'surface',
  'onSurface',
  'surfaceVariant',
  'onSurfaceVariant',
  'surfaceDim',
  'surfaceBright',
  'surfaceContainerLowest',
  'surfaceContainerLow',
  'surfaceContainer',
  'surfaceContainerHigh',
  'surfaceContainerHighest',
  'outline',
  'outlineVariant',
  'shadow',
  'scrim',
  'inverseSurface',
  'inverseOnSurface',
  'inversePrimary',
  'success',
  'onSuccess',
  'successContainer',
  'onSuccessContainer',
  'warning',
  'onWarning',
  'warningContainer',
  'onWarningContainer',
] as const;

export type FallbackColorToken = (typeof FALLBACK_COLOR_TOKENS)[number];

export type BaseColorSchemes = Record<ThemeMode, Record<FallbackColorToken, string>>;

export const BASE_COLOR_SCHEMES: BaseColorSchemes = {
  light: {
    primary: '#0053db',
    onPrimary: '#ffffff',
    primaryContainer: '#dbe1ff',
    onPrimaryContainer: '#00174b',
    secondary: '#595e72',
    onSecondary: '#ffffff',
    secondaryContainer: '#dde1f9',
    onSecondaryContainer: '#161b2c',
    tertiary: '#745470',
    onTertiary: '#ffffff',
    tertiaryContainer: '#ffd6f8',
    onTertiaryContainer: '#2b122b',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#410002',
    background: '#fefbff',
    onBackground: '#1b1b1f',
    surface: '#fefbff',
    onSurface: '#1b1b1f',
    surfaceVariant: '#e2e2ec',
    onSurfaceVariant: '#45464f',
    surfaceDim: '#e9e7ec',
    surfaceBright: '#fefbff',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#fbf8fd',
    surfaceContainer: '#f5f3f7',
    surfaceContainerHigh: '#efedf1',
    surfaceContainerHighest: '#e9e7ec',
    outline: '#757680',
    outlineVariant: '#c5c6d0',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#303034',
    inverseOnSurface: '#f2f0f4',
    inversePrimary: '#b4c5ff',
    success: '#006d43',
    onSuccess: '#ffffff',
    successContainer: '#72fcb4',
    onSuccessContainer: '#002111',
    warning: '#994704',
    onWarning: '#ffffff',
    warningContainer: '#ffdbc9',
    onWarningContainer: '#321200',
  },
  dark: {
    primary: '#b4c5ff',
    onPrimary: '#002a78',
    primaryContainer: '#003ea8',
    onPrimaryContainer: '#dbe1ff',
    secondary: '#c1c5dd',
    onSecondary: '#2b3042',
    secondaryContainer: '#414659',
    onSecondaryContainer: '#dde1f9',
    tertiary: '#e2bbdb',
    onTertiary: '#422741',
    tertiaryContainer: '#5a3d58',
    onTertiaryContainer: '#ffd6f8',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffb4ab',
    background: '#1b1b1f',
    onBackground: '#e4e2e6',
    surface: '#1b1b1f',
    onSurface: '#e4e2e6',
    surfaceVariant: '#45464f',
    onSurfaceVariant: '#c5c6d0',
    surfaceDim: '#1f1f23',
    surfaceBright: '#555458',
    surfaceContainerLowest: '#17171b',
    surfaceContainerLow: '#2c2c2f',
    surfaceContainer: '#343438',
    surfaceContainerHigh: '#3d3d41',
    surfaceContainerHighest: '#46464a',
    outline: '#8f909a',
    outlineVariant: '#45464f',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#e4e2e6',
    inverseOnSurface: '#303034',
    inversePrimary: '#0053db',
    success: '#52df9a',
    onSuccess: '#003921',
    successContainer: '#005232',
    onSuccessContainer: '#72fcb4',
    warning: '#ffb68c',
    onWarning: '#532200',
    warningContainer: '#753400',
    onWarningContainer: '#ffdbc9',
  },
};
