name: Deploy to GitHub Pages (peaceiris)

on:
  push:
    branches:
      - main # your default branch

# IMPORTANT: allow git push to gh-pages
permissions:
  contents: write # <-- required for peaceiris (it pushes via git)
  # pages/id-token are NOT needed here

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # upgrade to v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # LTS/current
          cache: npm

      - name: Install dependencies
        run: npm ci # faster & reproducible

      - name: Build
        run: npm run build

      - name: SPA fallback (optional but recommended)
        run: cp dist/index.html dist/404.html
        # English comment: GitHub Pages serves 404.html on unknown routes, useful for SPA routing

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # uses repo GITHUB_TOKEN
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: false # creates .nojekyll
          # English comment: peaceiris will commit and push to gh-pages
